import { SEGMENTS } from "./segments";

const PROPERTYMANAGEMENT = `${SEGMENTS.APP.PROPERTYMANAGEMENT}`
const ACCESSMANAGEMENT = `${SEGMENTS.APP.ACCESSMANAGEMENT}`
const LEASEMANAGEMENT = `${PROPERTYMANAGEMENT}/${SEGMENTS.APP.LEASEMANAGEMENT}`

export const API_URLS = {
        
        "receipts": `${LEASEMANAGEMENT}/${SEGMENTS.LEASEMANAGEMENT.RECEIPTS}`,
        "roles": `${ACCESSMANAGEMENT}/${SEGMENTS.ACCESSMANAGEMENT.ROLES}`
}